#!/usr/bin/with-contenv sh

echo "host all all 0.0.0.0/0 trust" >> /config/postgres/pg_hba.conf
echo "listen_addresses = '*'" >> /config/postgres/postgresql.conf

echo "Starting postgres..."
s6-setuidgid postgres postgres
